# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4feb5a2144d199fd263e041e5213b2b350c08e37ab77a28823be23626a0ef3d52577e7839896c7947a3dff3d16db2cec614495a18f5edeef3f7fe391b9a11987

test:
  secret_key_base: f54f52a0b50f78b246ed2b7a57d9f506f2492ba2afc1579188d3f6c274b1ac5ed3643ad3f4458c7f951ed670513dfc7baf7d6559392b0af64850cb8f20f0c3d1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
